POST http://localhost:8000/api/role/createrole HTTP/1.1
Content-Type: application/json

{
    "role_name": "scholar",
    "role_description": "scholar"
}

######

POST http://localhost:8000/api/school/create HTTP/1.1
Content-Type: application/json

{
    "school_name": "USTP",
    "address": "ustp"
}

######

POST http://localhost:8000/api/baranggay/create HTTP/1.1
Content-Type: application/json

{
    "baranggay_name": "lapasan",
    "address": "lapasan"
}

######

POST http://localhost:8000/api/scholartype/create HTTP/1.1
Content-Type: application/json

{
    "scholar_type_name": "coordinator"
}

######

POST http://localhost:8000/api/user/createuser HTTP/1.1
Content-Type: application/json

{
    "email": "craususrhyle@gmail.com",
    "password": "rairudesu"
}

######

POST http://localhost:8000/api/user/createscholar HTTP/1.1
Content-Type: application/json

{
    "firstname": "rhyle",
    "lastname": "crausus",
    "age": "22",
    "address": "lapasan",
    "mobilenumber": "09460728560",
    "user_id": 3,
    "school_id": 1,
    "baranggay_id": 1
}

######

POST http://localhost:8000/api/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "craususrhyle1@gmail.com",
    "password": "rairudesu1234"
}