###### ROLES

POST http://localhost:8000/api/role/createrole HTTP/1.1
Content-Type: application/json

{
    "role_name": "admin",
    "role_description": "admin"
}

######

POST http://localhost:8000/api/role/createrole HTTP/1.1
Content-Type: application/json

{
    "role_name": "scholar",
    "role_description": "scholar"
}

###### SCHOOL

POST http://localhost:8000/api/school/create HTTP/1.1
Content-Type: application/json

{
    "school_name": "Liceo",
    "address": "Carmen"
}

###### BARANGGAY

POST http://localhost:8000/api/baranggay/create HTTP/1.1
Content-Type: application/json

{
    "baranggay_name": "Carmen",
    "address": "Carmen"
}

###### SCHOLAR TYPE

POST http://localhost:8000/api/scholartype/create HTTP/1.1
Content-Type: application/json

{
    "scholar_type_name": "scholar"
}

######

POST http://localhost:8000/api/scholartype/create HTTP/1.1
Content-Type: application/json

{
    "scholar_type_name": "scholar leader"
}

###### ADMIN TYPE

POST http://localhost:8000/api/admintype/create HTTP/1.1
Content-Type: application/json

{
    "admin_type_name": "developer"
}

######

POST http://localhost:8000/api/admintype/create HTTP/1.1
Content-Type: application/json

{
    "admin_type_name": "CSO"
}

######

POST http://localhost:8000/api/admintype/create HTTP/1.1
Content-Type: application/json

{
    "admin_type_name": "School"
}

######

POST http://localhost:8000/api/admintype/create HTTP/1.1
Content-Type: application/json

{
    "admin_type_name": "Community"
}

###### USER CREATION (Can be either SCHOLAR or ADMIN - Default SCHOLARS) (for admins - change roleid in the database)

POST http://localhost:8000/api/user/createuser HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "test@gmail.com",
    "password": "test123"
}

###### SCHOLAR CREATION

POST http://localhost:8000/api/user/createscholar HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "firstname": "drae",
    "lastname": "cole",
    "age": "23",
    "address": "dddd",
    "mobilenumber": "09123456789",
    "yearlevel": "4th year",
    "scholar_type_id": 1,
    "user_id": 6,
    "school_id": 1,
    "baranggay_id": 1
}

###### ADMIN CREATION

POST http://localhost:8000/api/user/createadmin HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "admin_name": "Admin what",
    "admin_type_id": 4,
    "user_id": 4
}

###### ADMIN LOGIN

POST http://localhost:8000/api/user/admin/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "craususrhyleadmin@gmail.com",
    "password": "rairudesu"
}

###### SCHOLAR'S INFO

GET http://localhost:8000/api/user/scholar/me/show HTTP/1.1
Content-Type: application/json
Authorization: Bearer 59|BtuzcQyTnwgbeKVRpBbR9OoAtHa8xXP7zOfprBBXcc379611

###### SCHOLAR'S RETURN SERVICE

GET http://localhost:8000/api/events/scholars/return-service-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 78|sx64xhmbswcAtpNGnRrOwnReajgceYd6aTJCH0KT972a9075createScholarType

###### FAQS CREATION

POST http://localhost:8000/api/faqs/create HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 146|vngOGVnDydEeGJptAAOvJ0C4xLB8sQM7lyGQZb2W96d061a0

{
    "question": "Are you there?",
    "answer": "Yes why is that?"
}

###### GETTING FAQS

GET http://localhost:8000/api/faqs/getfaqs HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 150|LbtMnc1c3Wulgr7RGEYRBkt4DRnXj017IBbwT7BWd4b365dd
